### ISSUE TITLE
Unit Test for circropper()

### ISSUE THREAD

**Issue by Keanna-K** [UBC-MDS/pyimager#20]
### Create unit test function : `test_circropper()` 

- should contain 2-3 edge cases
- ensure tests cover all branches (i.e. tests cases for all outcomes of an 'if' statement)
- write documentation for the unit test function
- update code documentation if any changes occur
- use `pytest` package to ensure the code passes the unit test

**Comment by Keanna-K** [comment]
Currently, we have two separate test functions for circropper(). I think these should be combined into one unit test as per the milestone 2 instructions.
Also, the test_circropper_input_value() function prints "not error happens" . I think this sentence is supposed to be "no error happens"?  additionally, this should be contained within an assert call so that it does not erroneously pass when using pytest

**Comment by clsu22** [comment]
I have merged all tests for `circropper()` into one test function `test_circropper()`. Also fixed the unit tests including wrong error message.
