### ISSUE TITLE
Unit Test for reducolor

### ISSUE THREAD

**Issue by Keanna-K** [UBC-MDS/pyimager#23]
### Create unit test function : `test_reducolor()` 

- should contain 2-3 edge cases
- ensure tests cover all branches (i.e. tests cases for all outcomes of an 'if' statement)
- write documentation for the unit test function
- update code documentation if any changes occur
- use `pytest` package to ensure the code passes the unit test

**Comment by zoepan00** [comment]
#38 test passed
