### ISSUE TITLE
Code Function circropper()

### ISSUE THREAD

**Issue by Keanna-K** [UBC-MDS/pyimager#25]
- write the function body 
- update the documentation as required
- include exception handling 
      - handles incorrect input and other errors 
      - the exceptions should have useful error messages
      - all exceptions should be tested (ie. included in the function's unit test #20)

**Comment by Keanna-K** [comment]
As the function saves the output image automatically, an output image is created in our package directory when we run pytest. We can either add a line to the end of the unit test to delete the output image or make the output_path optional with default null.

**Comment by clsu22** [comment]
Yes, I see. I have removed the automatic output code.

**Comment by Keanna-K** [comment]
closed with pull request #41
