### ISSUE TITLE
Milestone 1 feedback

### ISSUE THREAD

**Issue by yavyx** [UBC-MDS/pyimager#28]
- Great job overall, README is clear and the functions make sense. Some functions could use more detailed descriptions.
- Is there are a reason why `reducolor` is in a separate script?
- Missing Clara's e-mail in contributors.

**Comment by zoepan00** [comment]
Thank you Javier. It's all updated as per your suggestions. #29, #30

**Comment by Keanna-K** [comment]
Added more detailed description for img_filter() function to README.md with pr #36

**Comment by zoepan00** [comment]
more description for reducolor added #38
