### ISSUE TITLE
Edit/Create team-work documents

### ISSUE THREAD

**Issue by zoepan00** [UBC-MDS/pyimager#3]
- [x] CONTRIBUTORS.md
- [x] CONDUCT.md
- [x] team_work_contract.md
- [x] CONTRIBUTING.md

**Comment by Keanna-K** [comment]
Pull request #13, updates the contributors, contributing, and conduct files.
Still need to update team member email addresses in the contributors file.

**Comment by zoepan00** [comment]
I added my email address, will submit pr later
