### ISSUE TITLE
Additional Tests

### ISSUE THREAD

**Issue by Keanna-K** [UBC-MDS/pyimager#46]
- have code coverage communicated with codecov.io button in README
- Add additional test cases, need to achieve 90% branch coverage or higher

**Comment by Keanna-K** [comment]
The code coverage is now working and showing a 95% coverage in our READM.md :smile: 
The main places we are missing some code coverage is due to incorrect formatting or missing assertion error tests. You can see the exact lines being covered by following this [link](https://codecov.io/gh/UBC-MDS/pyimager) and selecting the file of interest. 

Formatting issues: circropper, imgfilter @clsu22 @Keanna-K 
Missing test cases: redusize @dataubc

**Comment by clsu22** [comment]
Thank you. I have fixed my formatting issues and coverage has been improved to 97%:)
